CREATE TABLE table1 (awesome NVARCHAR(255) NOT NULL UNIQUE);
GO
CREATE TABLE table2 (awesome NVARCHAR(255) NOT NULL UNIQUE);
GO
CREATE TABLE table3 (awesome NVARCHAR(255) NOT NULL UNIQUE);
GO
CREATE TABLE table4 (awesome NVARCHAR(255) NOT NULL UNIQUE);
GO